pipeline:
    name: harnessjava
    identifier: harnessjava
    allowStageExecutions: false
    projectIdentifier: POCjavaproject
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: HarbrahmGithub
                repoName: java
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: harnessgk
                          namespace: harnessgk
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: building code
                                identifier: building_code
                                spec:
                                    connectorRef: jfrog
                                    image: devjfrogy.jfrog.io/default-docker-remote/maven:latest
                                    command: mvn clean package
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: create and push image
                                identifier: create_and_push_image
                                spec:
                                    connectorRef: jfrog
                                    repo: devjfrogy.jfrog.io/harnesslocalrepo/javabuildimage
                                    tags:
                                        - "1.0"
