pipeline:
    name: javaspringbootpipeline
    identifier: javaspringbootpipeline
    allowStageExecutions: false
    projectIdentifier: Demo_Project
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.gitconnector
                repoName: java
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.AKSConnector
                          namespace: harnessdemo
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: building code
                                identifier: building_code
                                spec:
                                    connectorRef: Jfrog_harness_integration
                                    image: harnessdev.jfrog.io/default-docker-remote/maven:latest
                                    command: |-
                                        mvn --version
                                        mvn clean package
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: building and pushing
                                identifier: building_and_pushing
                                spec:
                                    connectorRef: Jfrog_harness_integration
                                    repo: harnessdev.jfrog.io/docker-local/javasprongboot
                                    tags:
                                        - latest
                                    dockerfile: Dockerfile
                                    context: "."
                          - step:
                                type: ArtifactoryUpload
                                name: upload artifact
                                identifier: upload_artifact
                                spec:
                                    connectorRef: artifactory
                                    target: lib/
                                    sourcePath: /harness/target/*.jar
