apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspring-deployment
  labels:
    app: javaspring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaspring
  template:
    metadata:
      labels:
        app: javaspring
    spec:
      containers:
      - name: javaspring
        image: harnessdev.jfrog.io/docker-local/javasprongboot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaspring-service
spec:
  selector:
    app: javaspring
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer
